server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: account-service
        uri: lb://account-service
        predicates:
        - Path=/accounts/**
        filters:
        - RewritePath=/accounts/(?<path>.*), /$\{path}
      - id: location-service
        uri: lb://location-service
        predicates:
        - Path=/locations/**
        filters:
        - RewritePath=/locations/(?<path>.*), /$\{path}
      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/organizations/**
        filters:
        - RewritePath=/organizations/(?<path>.*), /$\{path}
      - id: camera-service
        uri: lb://camera-service
        predicates:
        - Path=/cameras/**
        filters:
        - RewritePath=/cameras/(?<path>.*), /$\{path}
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employees/**
        filters:
        - RewritePath=/employees/(?<path>.*), /$\{path}
      - id: mail-service
        uri: lb://mail-service
        predicates:
        - Path=/mails/**
        filters:
        - RewritePath=/mails/(?<path>.*), /$\{path}
      - id: area-restriction-service
        uri: lb://area-restriction-service
        predicates:
        - Path=/area-restrictions/**
        filters:
        - RewritePath=/area-restrictions/(?<path>.*), /$\{path}
      - id: history-service
        uri: lb://history-service
        predicates:
        - Path=/histories/**
        filters:
        - RewritePath=/histories/(?<path>.*), /$\{path}
      - id: time-keeping-service
        uri: lb://time-keeping-service
        predicates:
        - Path=/time-keepings/**
        filters:
        - RewritePath=/time-keepings/(?<path>.*), /$\{path}
      - id: metadata-service
        uri: lb://metadata-service
        predicates:
        - Path=/metadatas/**
        filters:
        - RewritePath=/metadatas/(?<path>.*), /$\{path}
      - id: user-log-service
        uri: lb://user-log-service
        predicates:
        - Path=/user-logs/**
        filters:
        - RewritePath=/user-logs/(?<path>.*), /$\{path}
      - id: feature-service
        uri: lb://feature-service
        predicates:
        - Path=/features/**
        filters:
        - RewritePath=/features/(?<path>.*), /$\{path}
      - id: openapi
        uri: http://localhost:${server.port}
        predicates:
        - Path=/v3/api-docs/**
        filters:
        - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
  main:
    web-application-type: reactive

cors:
  allow: http://localhost:3005,*

springdoc:
  swagger-ui:
    urls:
      - name: account
        url: /v3/api-docs/account
      - name: location
        url: /v3/api-docs/location
      - name: organization
        url: /v3/api-docs/organization