server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
              
zuul:
  routes:
    account:
      path: /accounts/**
      serviceId: account-service
    organization:
      path: /organizations/**
      serviceId: organization-service
    location:
      path: /locations/**
      serviceId: location-service
    camera:
      path: /cameras/**
      serviceId: camera-service
    employee:
      path: /employees/**
      serviceId: employee-service
    mail:
      path: /mails/**
      serviceId: mail-service